# delelopment
system:
  # url前缀
  url-path-prefix: api
  # 接口版本, 紧跟url-path-prefix后
  api-version: v1
  # 程序监听端口
  port: 8088
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: true

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

mysql:
  # 用户名
  username: root
  # 密码
  password: 123456
  # 数据库名
  database: go_lim
  # 主机地址
  host: localhost
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 数据库表前缀(无需再末尾添加下划线, 程序内部自动处理)
  table-prefix: tb
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

# casbin配置
casbin:
  # 模型配置文件, 默认以conf目录为根目录
  model-path: 'rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: test jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 12
  # 刷新token最大过期时间, 小时
  max-refresh: 12

# 速率限制配置
rate-limit:
  # 访问最大限制, 次/秒
  max: 200